### ISSUE TITLE
Issue on "173 - How many Developers are in a Scrum Team?"

### ISSUE THREAD

**Issue by KevinMckk** [Ditectrev/Scrum-Product-Owner-PSPO-I-Practice-Tests-Exams-Questions-Answers#6]
According to https://scrumguides.org/scrum-guide.html

The Scrum Team is small enough to remain nimble and large enough to complete significant work within a Sprint, typically **10 or fewer** people.

```
### How many Developers are in a Scrum Team?

- [ ] 3 to 10.
- [ ] 1 to 9.
- [ ] 3 to 9.
- [x] 10 or fewer
```

**Comment by danieldanielecki** [comment]
`The Scrum Team consists of one Scrum Master, one Product Owner, and Developers.` The question is about Developers, and the current answer is correct.

We have another such a question about Scrum Team size, in different course, where the answer is indeed as you're suggesting: https://github.com/Ditectrev/Scrum-Master-I-PSM-I-Practice-Tests-Exams-Questions-Answers?tab=readme-ov-file#what-is-the-recommended-size-for-a-scrum-team-choose-the-best-answer.

**Comment by danieldanielecki** [comment]
and from another course https://github.com/Ditectrev/Scrum-Developer-I-PSD-I-Practice-Tests-Exams-Questions-Answers?tab=readme-ov-file#what-is-the-recommended-size-for-a-scrum-team-choose-the-best-answer
